// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package sqlc

import (
	"database/sql"
)

type User struct {
	ID        string
	Name      string
	Email     sql.NullString
	Cpf       sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
