// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteUser(ctx context.Context, id string) error
	ExistsUserByCpf(ctx context.Context, arg ExistsUserByCpfParams) (*User, error)
	ExistsUserByEmail(ctx context.Context, arg ExistsUserByEmailParams) (*User, error)
	GetPaginatedUsers(ctx context.Context, arg GetPaginatedUsersParams) ([]*User, error)
	GetUserById(ctx context.Context, id string) (*User, error)
	GetUsers(ctx context.Context) ([]*User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
